name: Lint check by black

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout Current Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install -U pip
      - name: Pip install black
        run: |
          pip install --force-reinstall black
      - name: Library version
        run: git describe --dirty --always --tags
      - name: Format check with black
        run: |
          black --check .
